In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Creating a empty dict, where I will save all parameters required for test data transformation

saved_dict = {}

In [ ]:
# Reading datasets
dfs = []
for i in range(1,5):
    path = '/content/drive/MyDrive/UNSW/CSV Files/UNSW-NB15_{}.csv'  # There are 4 input csv files
    dfs.append(pd.read_csv(path.format(i), header = None))
all_data = pd.concat(dfs).reset_index(drop=True)  # Concat all to a single df

<ipython-input-4-f9c534c03c56>:5: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs.append(pd.read_csv(path.format(i), header = None))
<ipython-input-4-f9c534c03c56>:5: DtypeWarning: Columns (3,39,47) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs.append(pd.read_csv(path.format(i), header = None))


In [ ]:
# This csv file contains names of all the features
df_col = pd.read_csv('/content/drive/MyDrive/UNSW/CSV Files/NUSW-NB15_features.csv', encoding='ISO-8859-1')

In [ ]:
# Making column names lower case, removing spaces
df_col['Name'] = df_col['Name'].apply(lambda x: x.strip().replace(' ', '').lower())

In [ ]:
# Renaming our dataframe with proper column names
all_data.columns = df_col['Name']

In [ ]:
# Saving useful info, later this will be used to transform raw test data
saved_dict['columns'] = df_col['Name'][df_col['Name']!='label'].tolist()

In [ ]:
del df_col

In [ ]:
all_data.shape

(2540047, 49)

In [ ]:
all_data.head()

Name       srcip  sport          dstip dsport proto state       dur  sbytes  \
0     59.166.0.0   1390  149.171.126.6     53   udp   CON  0.001055     132   
1     59.166.0.0  33661  149.171.126.9   1024   udp   CON  0.036133     528   
2     59.166.0.6   1464  149.171.126.7     53   udp   CON  0.001119     146   
3     59.166.0.5   3593  149.171.126.5     53   udp   CON  0.001209     132   
4     59.166.0.3  49664  149.171.126.0     53   udp   CON  0.001169     146   

Name  dbytes  sttl  ...  ct_ftp_cmd  ct_srv_src  ct_srv_dst ct_dst_ltm  \
0        164    31  ...           0           3           7          1   
1        304    31  ...           0           2           4          2   
2        178    31  ...           0          12           8          1   
3        164    31  ...           0           6           9          1   
4        178    31  ...           0           7           9          1   

Name  ct_src_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  \
0              3                 1                 1               1   
1              3                 1                 1               2   
2              2                 2                 1               1   
3              1                 1                 1               1   
4              1                 1                 1               1   

Name  attack_cat  label  
0            NaN      0  
1            NaN      0  
2            NaN      0  
3            NaN      0  
4            NaN      0  

[5 rows x 49 columns]

In [ ]:
all_data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2540047 entries, 0 to 2540046
Data columns (total 49 columns):
 #   Column            Dtype  
---  ------            -----  
 0   srcip             object 
 1   sport             object 
 2   dstip             object 
 3   dsport            object 
 4   proto             object 
 5   state             object 
 6   dur               float64
 7   sbytes            int64  
 8   dbytes            int64  
 9   sttl              int64  
 10  dttl              int64  
 11  sloss             int64  
 12  dloss             int64  
 13  service           object 
 14  sload             float64
 15  dload             float64
 16  spkts             int64  
 17  dpkts             int64  
 18  swin              int64  
 19  dwin              int64  
 20  stcpb             int64  
 21  dtcpb             int64  
 22  smeansz           int64  
 23  dmeansz           int64  
 24  trans_depth       int64  
 25  res_bdy_len       int64  
 26  sjit          

In [ ]:
# attack_cat 열에서 NaN 값을 "Normal"로 대체
all_data['attack_cat'] = all_data['attack_cat'].fillna('Normal').str.strip()

In [ ]:
class_names  = all_data['attack_cat'].unique()

In [ ]:
class_names

array(['Normal', 'Exploits', 'Reconnaissance', 'DoS', 'Generic',
       'Shellcode', 'Fuzzers', 'Worms', 'Backdoors', 'Analysis',
       'Backdoor'], dtype=object)

## Data cleaning and pre-processing

In [ ]:
# Missing Data Handling Module

def myPreprocessor(dataframe, handling_method, target_label_name):
    df = dataframe
    method = handling_method
    label = target_label_name

    #importing libraries
    import numpy as np
    import pandas as pd
    from sklearn import preprocessing

    for i in range(df.shape[1]):
        n = df.iloc[:,i].isnull().sum()
        if n > 0:
            print("There is some missing values")
            print(df.iloc[:,i].name)
            if df.iloc[:,i].dtype == 'object':
                print('object')
                df.iloc[:,i]=df.iloc[:,i].fillna(df.iloc[:,i].mode()[0])
            else:
                print('numerical')

                if method == 'mean':
                    df.iloc[:,i]=df.iloc[:,i].fillna(df.iloc[:,i].mean())
                elif method == 'median':
                    df.iloc[:,i]=df.iloc[:,i].fillna(df.iloc[:,i].median())
                elif method == 'ffill':
                    df.iloc[:,i]=df.iloc[:,i].fillna(method = 'ffill')

# Label Encoder for converting categorical values to numerical values

    obj_features = []

    # Decide which categorical variables you want to use in model
    for col_name in df.columns:
        if df[col_name].dtypes == 'object':
            unique_cat = len(df[col_name].unique())
            print("Feature '{col_name}' has {unique_cat} unique categories".format(col_name=col_name, unique_cat=unique_cat))
            obj_features.append(col_name)

    label_encoder = preprocessing.LabelEncoder()

    k = df[obj_features].shape[1]

    for i in range(k):
        name=obj_features
        name[i]
        df[name[i]]= label_encoder.fit_transform(df[name[i]])


# Feature scaling - Normalization

    features_data=df.drop(label,axis=1)
    class_data=df[label]
    ###
    cols_name = features_data.columns

    minmax_scaler=preprocessing.MinMaxScaler()
    scaled =minmax_scaler.fit_transform(features_data)

    normalize_data = pd.DataFrame(scaled, columns = cols_name)

    return normalize_data, class_data, label_encoder

In [ ]:
# Missing Data Handling Module

def myBinaryPreprocessor(dataframe, handling_method, target_label_name):
    df = dataframe
    method = handling_method
    label = target_label_name

    #importing libraries
    import numpy as np
    import pandas as pd
    from sklearn import preprocessing

    for i in range(df.shape[1]):
        n = df.iloc[:,i].isnull().sum()
        if n > 0:
            print("There is some missing values")
            print(df.iloc[:,i].name)
            if df.iloc[:,i].dtype == 'object':
                print('object')
                df.iloc[:,i]=df.iloc[:,i].fillna(df.iloc[:,i].mode()[0])
            else:
                print('numerical')

                if method == 'mean':
                    df.iloc[:,i]=df.iloc[:,i].fillna(df.iloc[:,i].mean())
                elif method == 'median':
                    df.iloc[:,i]=df.iloc[:,i].fillna(df.iloc[:,i].median())
                elif method == 'ffill':
                    df.iloc[:,i]=df.iloc[:,i].fillna(method = 'ffill')

# Label Encoder for converting categorical values to numerical values

    obj_features = []

    # Decide which categorical variables you want to use in model
    for col_name in df.columns:
        if df[col_name].dtypes == 'object':
            unique_cat = len(df[col_name].unique())
            print("Feature '{col_name}' has {unique_cat} unique categories".format(col_name=col_name, unique_cat=unique_cat))
            obj_features.append(col_name)

    label_encoder = preprocessing.LabelEncoder()

    k = df[obj_features].shape[1]

    for i in range(k):
        name=obj_features
        name[i]
        df[name[i]]= label_encoder.fit_transform(df[name[i]])


# Feature scaling - Normalization

    features_data=df.drop(label,axis=1)
    class_data=df[label]
    ###
    cols_name = features_data.columns

    minmax_scaler=preprocessing.MinMaxScaler()
    scaled =minmax_scaler.fit_transform(features_data)

    normalize_data = pd.DataFrame(scaled, columns = cols_name)

    return normalize_data, class_data, label_encoder

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn import preprocessing
from sklearn.metrics import classification_report, accuracy_score, recall_score, precision_score, f1_score, confusion_matrix
import tensorflow as tf
from tensorflow.keras import models, layers, optimizers, initializers
from tensorflow.keras.utils import to_categorical
#from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from imblearn.over_sampling import SMOTE
from tensorflow.keras.callbacks import ReduceLROnPlateau

In [ ]:
def Remove_dump_values(data, cols):
    for col in cols:
        data[col] = np.where(data[col] == '-', np.nan, data[col])
    return data

In [ ]:
cols = all_data.columns
df = Remove_dump_values(all_data, cols)

In [ ]:
df

Name            srcip  sport           dstip dsport proto state       dur  \
0          59.166.0.0   1390   149.171.126.6     53   udp   CON  0.001055   
1          59.166.0.0  33661   149.171.126.9   1024   udp   CON  0.036133   
2          59.166.0.6   1464   149.171.126.7     53   udp   CON  0.001119   
3          59.166.0.5   3593   149.171.126.5     53   udp   CON  0.001209   
4          59.166.0.3  49664   149.171.126.0     53   udp   CON  0.001169   
...               ...    ...             ...    ...   ...   ...       ...   
2540042    59.166.0.5  33094   149.171.126.7  43433   tcp   FIN  0.087306   
2540043    59.166.0.7  20848   149.171.126.4     21   tcp   CON  0.365058   
2540044    59.166.0.3  21511   149.171.126.9     21   tcp   CON  6.335154   
2540045    59.166.0.9  35433   149.171.126.0     80   tcp   CON  2.200934   
2540046  175.45.176.0  17293  149.171.126.17    110   tcp   CON  0.942984   

Name     sbytes    dbytes  sttl  ...  ct_ftp_cmd  ct_srv_src  ct_srv_dst  \
0         132.0     164.0  31.0  ...           0         3.0         7.0   
1         528.0     304.0  31.0  ...           0         2.0         4.0   
2         146.0     178.0  31.0  ...           0        12.0         8.0   
3         132.0     164.0  31.0  ...           0         6.0         9.0   
4         146.0     178.0  31.0  ...           0         7.0         9.0   
...         ...       ...   ...  ...         ...         ...         ...   
2540042   320.0    1828.0  31.0  ...                     1.0         2.0   
2540043   456.0     346.0  31.0  ...           2         2.0         2.0   
2540044  1802.0    2088.0  31.0  ...           2         2.0         2.0   
2540045  3498.0  166054.0  31.0  ...                     1.0         1.0   
2540046   574.0     676.0  62.0  ...                     1.0         1.0   

Name    ct_dst_ltm  ct_src_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  \
0              1.0         3.0               1.0               1.0   
1              2.0         3.0               1.0               1.0   
2              1.0         2.0               2.0               1.0   
3              1.0         1.0               1.0               1.0   
4              1.0         1.0               1.0               1.0   
...            ...         ...               ...               ...   
2540042        3.0         3.0               1.0               1.0   
2540043        2.0         2.0               2.0               2.0   
2540044        4.0         2.0               2.0               2.0   
2540045        2.0         4.0               2.0               2.0   
2540046        2.0         4.0               2.0               2.0   

Name     ct_dst_src_ltm  attack_cat  label  
0                   1.0      Normal    0.0  
1                   2.0      Normal    0.0  
2                   1.0      Normal    0.0  
3                   1.0      Normal    0.0  
4                   1.0      Normal    0.0  
...                 ...         ...    ...  
2540042             3.0      Normal    0.0  
2540043             2.0      Normal    0.0  
2540044             2.0      Normal    0.0  
2540045             2.0      Normal    0.0  
2540046             2.0    Exploits    1.0  

[2540047 rows x 49 columns]

In [ ]:
df_multi = df.copy()

In [ ]:
df_binary = df.copy()

In [ ]:
# attack_cat 열에서 Backdoor 값을 Backdoors로 변경
df['attack_cat'] = df['attack_cat'].replace('Backdoor', 'Backdoors')

In [ ]:
# attack_cat 열에서 Backdoor 값을 Backdoors로 변경
df_multi['attack_cat'] = df_multi['attack_cat'].replace('Backdoor', 'Backdoors')

In [ ]:
# 'attack_cat' 열이 'Normal'인 데이터 삭제
df_multi = df_multi[df_multi['attack_cat'] != 'Normal']

In [ ]:
df_multi['attack_cat'].unique()

array(['Exploits', 'Reconnaissance', 'DoS', 'Generic', 'Shellcode',
       'Fuzzers', 'Worms', 'Backdoors', 'Analysis'], dtype=object)

In [ ]:
df_multi['ct_flw_http_mthd'] = df_multi.ct_flw_http_mthd.fillna(value=0)

<ipython-input-28-95f69ee3d64a>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_multi['ct_flw_http_mthd'] = df_multi.ct_flw_http_mthd.fillna(value=0)


In [ ]:
df_multi['is_ftp_login'] = (df_multi.is_ftp_login.fillna(value=0)).astype(int)

<ipython-input-29-5a85573168cc>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_multi['is_ftp_login'] = (df_multi.is_ftp_login.fillna(value=0)).astype(int)


In [ ]:
df_multi.drop(['sport', 'dsport', 'label','service', 'ct_ftp_cmd', 'srcip', 'dstip'], axis=1, inplace = True)

In [ ]:
df_multi.isnull().sum()

Name
proto               0
state               0
dur                 0
sbytes              0
dbytes              0
sttl                0
dttl                0
sloss               0
dloss               0
sload               0
dload               0
spkts               0
dpkts               0
swin                0
dwin                0
stcpb               0
dtcpb               0
smeansz             0
dmeansz             0
trans_depth         0
res_bdy_len         0
sjit                0
djit                0
stime               0
ltime               0
sintpkt             0
dintpkt             0
tcprtt              0
synack              0
ackdat              0
is_sm_ips_ports     0
ct_state_ttl        0
ct_flw_http_mthd    0
is_ftp_login        0
ct_srv_src          0
ct_srv_dst          0
ct_dst_ltm          0
ct_src_ltm          0
ct_src_dport_ltm    0
ct_dst_sport_ltm    0
ct_dst_src_ltm      0
attack_cat          0
dtype: int64

In [ ]:
x, y, multi_label_encoder = myPreprocessor(df_multi, 'mean', 'attack_cat')

Feature 'proto' has 129 unique categories
Feature 'state' has 7 unique categories
Feature 'attack_cat' has 9 unique categories


In [ ]:
# 'attack_cat' 열을 다중 클래스 타겟 라벨로 설정
y_multi = df_multi['attack_cat'].values

In [ ]:
unique_classes, class_counts = np.unique(y_multi, return_counts=True)
for cls, count in zip(unique_classes, class_counts):
    print(f"Class {cls}: {count}")

Class 0: 2677
Class 1: 2329
Class 2: 16353
Class 3: 44525
Class 4: 24246
Class 5: 215481
Class 6: 13987
Class 7: 1511
Class 8: 174


In [ ]:
# 각 인코딩된 값과 원래 클래스의 매핑 출력
for index, class_label in enumerate(multi_label_encoder.classes_):
    print(f"Value {index}: {class_label}")


Value 0: Analysis
Value 1: Backdoors
Value 2: DoS
Value 3: Exploits
Value 4: Fuzzers
Value 5: Generic
Value 6: Reconnaissance
Value 7: Shellcode
Value 8: Worms


In [ ]:
x

Name       proto     state           dur    sbytes    dbytes      sttl  \
0       0.898438  0.666667  3.500028e-07  0.000051  0.000000  0.996078   
1       0.851562  0.500000  4.002348e-03  0.000064  0.001743  0.243137   
2       0.851562  0.500000  3.984015e-02  0.000095  0.000018  0.996078   
3       0.851562  0.500000  2.919856e-03  0.000569  0.000018  0.996078   
4       0.851562  0.500000  3.176692e-03  0.000059  0.000018  0.996078   
...          ...       ...           ...       ...       ...       ...   
321278  0.898438  0.666667  1.666680e-08  0.000008  0.000000  0.996078   
321279  0.851562  0.333333  1.571652e-02  0.000040  0.000046  0.243137   
321280  0.851562  0.333333  4.299042e-02  0.018800  0.000089  0.243137   
321281  0.851562  0.333333  4.299042e-02  0.018800  0.000089  0.243137   
321282  0.851562  0.333333  1.571652e-02  0.000040  0.000046  0.243137   

Name        dttl     sloss     dloss         sload  ...  ct_state_ttl  \
0       0.000000  0.000000  0.000000  2.315743e-02  ...      0.333333   
1       0.996047  0.000376  0.001816  4.684439e-06  ...      0.166667   
2       0.996047  0.001128  0.000182  7.070172e-07  ...      0.166667   
3       0.996047  0.000752  0.000182  5.784349e-05  ...      0.166667   
4       0.996047  0.000376  0.000182  5.327199e-06  ...      0.166667   
...          ...       ...       ...           ...  ...           ...   
321278  0.000000  0.000000  0.000000  7.615230e-02  ...      0.333333   
321279  0.996047  0.000940  0.001090  7.466455e-07  ...      0.500000   
321280  0.996047  0.019365  0.000182  1.391144e-04  ...      0.500000   
321281  0.996047  0.019365  0.000182  1.391144e-04  ...      0.500000   
321282  0.996047  0.000940  0.001090  7.466455e-07  ...      0.500000   

Name    ct_flw_http_mthd  is_ftp_login  ct_srv_src  ct_srv_dst  ct_dst_ltm  \
0               0.000000           0.0    0.000000    0.000000    0.000000   
1               0.033333           0.0    0.030303    0.015152    0.015152   
2               0.033333           0.0    0.060606    0.015152    0.015152   
3               0.000000           0.0    0.000000    0.000000    0.000000   
4               0.033333           0.0    0.030303    0.000000    0.000000   
...                  ...           ...         ...         ...         ...   
321278          0.000000           0.0    0.212121    0.212121    0.212121   
321279          0.000000           0.0    0.015152    0.000000    0.015152   
321280          0.066667           0.0    0.015152    0.000000    0.015152   
321281          0.066667           0.0    0.000000    0.000000    0.015152   
321282          0.000000           0.0    0.000000    0.000000    0.015152   

Name    ct_src_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  
0         0.000000          0.000000          0.000000        0.000000  
1         0.000000          0.000000          0.000000        0.000000  
2         0.000000          0.000000          0.000000        0.000000  
3         0.000000          0.000000          0.000000        0.000000  
4         0.000000          0.000000          0.000000        0.000000  
...            ...               ...               ...             ...  
321278    0.212121          0.212121          0.378378        0.212121  
321279    0.045455          0.015152          0.027027        0.015152  
321280    0.045455          0.015152          0.027027        0.015152  
321281    0.045455          0.015152          0.027027        0.015152  
321282    0.045455          0.015152          0.027027        0.015152  

[321283 rows x 41 columns]

In [ ]:
print(x.head())

Name     proto     state           dur    sbytes    dbytes      sttl  \
0     0.898438  0.666667  3.500028e-07  0.000051  0.000000  0.996078   
1     0.851562  0.500000  4.002348e-03  0.000064  0.001743  0.243137   
2     0.851562  0.500000  3.984015e-02  0.000095  0.000018  0.996078   
3     0.851562  0.500000  2.919856e-03  0.000569  0.000018  0.996078   
4     0.851562  0.500000  3.176692e-03  0.000059  0.000018  0.996078   

Name      dttl     sloss     dloss         sload  ...  ct_state_ttl  \
0     0.000000  0.000000  0.000000  2.315743e-02  ...      0.333333   
1     0.996047  0.000376  0.001816  4.684439e-06  ...      0.166667   
2     0.996047  0.001128  0.000182  7.070172e-07  ...      0.166667   
3     0.996047  0.000752  0.000182  5.784349e-05  ...      0.166667   
4     0.996047  0.000376  0.000182  5.327199e-06  ...      0.166667   

Name  ct_flw_http_mthd  is_ftp_login  ct_srv_src  ct_srv_dst  ct_dst_ltm  \
0             0.000000           0.0    0.000000    0.000000    

In [ ]:
y.value_counts()

attack_cat
5    215481
3     44525
4     24246
2     16353
6     13987
0      2677
1      2329
7      1511
8       174
Name: count, dtype: int64

## 이진분류용

In [ ]:
# attack_cat 열에서 Backdoor 값을 Backdoors로 변경
df_binary['attack_cat'] = df_binary['attack_cat'].replace('Backdoor', 'Backdoors')

In [ ]:
df_binary['ct_flw_http_mthd'] = df_binary.ct_flw_http_mthd.fillna(value=0)

In [ ]:
df_binary['is_ftp_login'] = (df_binary.is_ftp_login.fillna(value=0)).astype(int)

In [ ]:
df_binary.drop(['sport', 'dsport', 'attack_cat','service', 'ct_ftp_cmd', 'srcip', 'dstip'], axis=1, inplace = True)

In [ ]:
df_binary['label'].value_counts()

label
0.0    2218764
1.0     321283
Name: count, dtype: int64

In [ ]:
x_binary, y_binary, binary_label_encoder = myBinaryPreprocessor(df_binary, 'mean', 'label')

Feature 'proto' has 135 unique categories
Feature 'state' has 16 unique categories


In [ ]:
x_binary

Name        proto     state           dur    sbytes    dbytes      sttl  \
0        0.895522  0.133333  1.200687e-07  0.000009  0.000011  0.121569   
1        0.895522  0.133333  4.112267e-06  0.000037  0.000021  0.121569   
2        0.895522  0.133333  1.273525e-07  0.000010  0.000012  0.121569   
3        0.895522  0.133333  1.375953e-07  0.000009  0.000011  0.121569   
4        0.895522  0.133333  1.330429e-07  0.000010  0.000012  0.121569   
...           ...       ...           ...       ...       ...       ...   
2540042  0.850746  0.333333  9.936224e-06  0.000022  0.000125  0.121569   
2540043  0.850746  0.133333  4.154695e-05  0.000032  0.000024  0.121569   
2540044  0.850746  0.133333  7.209987e-04  0.000126  0.000142  0.121569   
2540045  0.850746  0.133333  2.504865e-04  0.000244  0.011329  0.121569   
2540046  0.850746  0.133333  1.073202e-04  0.000040  0.000046  0.243137   

Name         dttl     sloss     dloss         sload  ...  ct_state_ttl  \
0        0.114173  0.000000  0.000000  8.357948e-05  ...           0.0   
1        0.114173  0.000000  0.000000  1.464196e-05  ...           0.0   
2        0.114173  0.000000  0.000000  8.715673e-05  ...           0.0   
3        0.114173  0.000000  0.000000  7.293329e-05  ...           0.0   
4        0.114173  0.000000  0.000000  8.342890e-05  ...           0.0   
...           ...       ...       ...           ...  ...           ...   
2540042  0.114173  0.000188  0.000363  4.085783e-06  ...           0.0   
2540043  0.114173  0.000376  0.000363  1.460223e-06  ...           0.0   
2540044  0.114173  0.001316  0.001634  3.682097e-07  ...           0.0   
2540045  0.114173  0.000376  0.010350  2.086926e-06  ...           0.0   
2540046  0.992126  0.000940  0.001090  7.466455e-07  ...           0.5   

Name     ct_flw_http_mthd  is_ftp_login  ct_srv_src  ct_srv_dst  ct_dst_ltm  \
0                0.000000           0.0    0.030303    0.090909    0.000000   
1                0.000000           0.0    0.015152    0.045455    0.015152   
2                0.000000           0.0    0.166667    0.106061    0.000000   
3                0.000000           0.0    0.075758    0.121212    0.000000   
4                0.000000           0.0    0.090909    0.121212    0.000000   
...                   ...           ...         ...         ...         ...   
2540042          0.000000           0.0    0.000000    0.015152    0.030303   
2540043          0.000000           0.5    0.015152    0.015152    0.015152   
2540044          0.000000           0.5    0.015152    0.015152    0.045455   
2540045          0.055556           0.0    0.000000    0.000000    0.015152   
2540046          0.000000           0.0    0.000000    0.000000    0.015152   

Name     ct_src_ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  
0          0.030303          0.000000          0.000000        0.000000  
1          0.030303          0.000000          0.000000        0.015152  
2          0.015152          0.015152          0.000000        0.000000  
3          0.000000          0.000000          0.000000        0.000000  
4          0.000000          0.000000          0.000000        0.000000  
...             ...               ...               ...             ...  
2540042    0.030303          0.000000          0.000000        0.030303  
2540043    0.015152          0.015152          0.016949        0.015152  
2540044    0.015152          0.015152          0.016949        0.015152  
2540045    0.045455          0.015152          0.016949        0.015152  
2540046    0.045455          0.015152          0.016949        0.015152  

[2540047 rows x 41 columns]

In [ ]:
y_binary.value_counts()

label
0.0    2218764
1.0     321283
Name: count, dtype: int64

In [ ]:
y.value_counts()

attack_cat
5    215481
3     44525
4     24246
2     16353
6     13987
0      2677
1      2329
7      1511
8       174
Name: count, dtype: int64

## Data Visualization

In [ ]:
x_train_attack_multi = np.array(x)
y_train_attack_multi = np.array(y)

In [ ]:
# 원본 데이터셋의 전체 인덱스 생성
original_indices = np.arange(len(x_train_attack_multi))  # x_train_attack_multi의 행 인덱스

# 데이터를 80:10:10 비율로 나누기 (인덱스 포함)
x_train_multi, x_temp_multi, y_train_multi, y_temp_multi, train_indices, temp_indices = train_test_split(
    x_train_attack_multi, y_train_attack_multi, original_indices, test_size=0.2, random_state=42, stratify=y_train_attack_multi
)

x_val_multi, x_test_multi, y_val_multi, y_test_multi, val_indices, test_indices = train_test_split(
    x_temp_multi, y_temp_multi, temp_indices, test_size=0.5, random_state=42, stratify=y_temp_multi
)




In [ ]:
from collections import Counter

print("Original Distribution: ", Counter(y_train_multi))

Original Distribution:  Counter({5: 172384, 3: 35620, 4: 19397, 2: 13082, 6: 11190, 0: 2142, 1: 1863, 7: 1209, 8: 139})


In [ ]:
# Step 1: 언더샘플링
# 가장 많은 클래스(7)를 두 번째로 많은 클래스(6)의 수에 맞추기

undersample = RandomUnderSampler(sampling_strategy={5: 35620}, random_state=42)
x_under, y_under = undersample.fit_resample(x_train_multi, y_train_multi)


In [ ]:
from imblearn.over_sampling import SMOTE

# SMOTE 오버샘플링 적용
smote = SMOTE(sampling_strategy='auto', random_state=42)
x_train_attack_multi_resampled, y_train_attack_multi_resampled = smote.fit_resample(x_under, y_under)

# 클래스 분포 확인
from collections import Counter
print("Original Distribution: ", Counter(y_train_multi))
print("After Undersampling: ", Counter(y_under))  # 언더샘플링 후 분포
print("After SMOTE Oversampling: ", Counter(y_train_attack_multi_resampled))
x_train_multi = x_train_attack_multi_resampled
y_train_multi = y_train_attack_multi_resampled

Original Distribution:  Counter({5: 172384, 3: 35620, 4: 19397, 2: 13082, 6: 11190, 0: 2142, 1: 1863, 7: 1209, 8: 139})
After Undersampling:  Counter({3: 35620, 5: 35620, 4: 19397, 2: 13082, 6: 11190, 0: 2142, 1: 1863, 7: 1209, 8: 139})
After SMOTE Oversampling:  Counter({0: 35620, 1: 35620, 2: 35620, 3: 35620, 4: 35620, 5: 35620, 6: 35620, 7: 35620, 8: 35620})


In [ ]:
# CNN 모델이 필요로 하는 형태로 데이터 차원 확장
x_train_multi = np.expand_dims(x_train_multi, axis=2)
x_test_multi = np.expand_dims(x_test_multi, axis=2)
x_val_multi = np.expand_dims(x_val_multi, axis=2)

# 테스트 데이터에 해당하는 원본 데이터셋의 인덱스
x_test_indices_multi = test_indices

In [ ]:
x_array_binary = np.array(x_binary)
y_array_binary = np.array(y_binary)

In [ ]:
# 원본 데이터셋의 전체 인덱스 생성
original_indices = np.arange(len(x_array_binary))  # 원본 데이터셋의 행 인덱스

# 데이터를 80:10:10 비율로 나누기 (인덱스 포함)
x_train_binary, x_temp_binary, y_train_binary, y_temp_binary, train_indices, temp_indices = train_test_split(
    x_array_binary, y_array_binary, original_indices, test_size=0.2, random_state=42, stratify=y_array_binary
)

x_val_binary, x_test_binary, y_val_binary, y_test_binary, val_indices, test_indices = train_test_split(
    x_temp_binary, y_temp_binary, temp_indices, test_size=0.5, random_state=42, stratify=y_temp_binary
)

# CNN 모델이 필요로 하는 형태로 데이터 차원 확장
x_train_binary = np.expand_dims(x_train_binary, axis=2)
x_test_binary = np.expand_dims(x_test_binary, axis=2)
x_val_binary = np.expand_dims(x_val_binary, axis=2)

# 테스트 데이터에 해당하는 원본 데이터셋의 인덱스
x_test_indices = test_indices

## Model

In [ ]:
# 첫 번째 모델 정의
cnn_binary = models.Sequential([
    layers.Conv1D(32, 3, activation='relu', padding='same', kernel_initializer='he_uniform', input_shape=(41, 1)),
    layers.Conv1D(32, 3, activation='relu', padding='same', kernel_initializer='he_uniform'),
    layers.MaxPooling1D(pool_size=2, strides=2),
    layers.Dropout(0.2),
    layers.BatchNormalization(),

    layers.Conv1D(64, 3, activation='relu', padding='same', kernel_initializer='he_uniform'),
    layers.Conv1D(64, 3, activation='relu', padding='same', kernel_initializer='he_uniform'),
    layers.MaxPooling1D(pool_size=2, strides=2),
    layers.Dropout(0.2),
    layers.BatchNormalization(),

    layers.Flatten(),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='sigmoid')  # 이진분류를 위한 출력층
])

# 모델 컴파일
cnn_binary.compile(optimizer='nadam', loss='binary_crossentropy', metrics=['accuracy'])

# 모델 학습
cnn_binary.fit(x_train_binary, y_train_binary,
               batch_size=256,
               epochs=15,
               validation_data=(x_val_binary, y_val_binary))


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/15
7938/7938 ━━━━━━━━━━━━━━━━━━━━ 42s 4ms/step - accuracy: 0.9877 - loss: 0.0269 - val_accuracy: 0.9903 - val_loss: 0.0181
Epoch 2/15
7938/7938 ━━━━━━━━━━━━━━━━━━━━ 34s 4ms/step - accuracy: 0.9904 - loss: 0.0185 - val_accuracy: 0.9908 - val_loss: 0.0176
Epoch 3/15
7938/7938 ━━━━━━━━━━━━━━━━━━━━ 31s 4ms/step - accuracy: 0.9908 - loss: 0.0176 - val_accuracy: 0.9915 - val_loss: 0.0168
Epoch 4/15
7938/7938 ━━━━━━━━━━━━━━━━━━━━ 30s 4ms/step - accuracy: 0.9915 - loss: 0.0168 - val_accuracy: 0.9916 - val_loss: 0.0166
Epoch 5/15
7938/7938 ━━━━━━━━━━━━━━━━━━━━ 31s 4ms/step - accuracy: 0.9918 - loss: 0.0166 - val_accuracy: 0.9921 - val_loss: 0.0160
Epoch 6/15
7938/7938 ━━━━━━━━━━━━━━━━━━━━ 31s 4ms/step - accuracy: 0.9918 - loss: 0.0165 - val_accuracy: 0.9913 - val_loss: 0.0185
Epoch 7/15
7938/7938 ━━━━━━━━━━━━━━━━━━━━ 31s 4ms/step - accuracy: 0.9919 - loss: 0.0163 - val_accuracy: 0.9919 - val_loss: 0.0159
Epoch 8/15
7938/7938 ━━━━━━━━━━━━━━━━━━━━ 41s 4ms/step - accuracy: 0.9919 - loss: 0

In [ ]:
# 두 번째 모델 정의
cnn_multi = models.Sequential([
    layers.Conv1D(128, 3, activation='relu', padding='same', input_shape=(41, 1)),
    layers.Conv1D(128, 3, activation='relu', padding='same'),
    layers.MaxPooling1D(pool_size=2),
    layers.Dropout(0.3),

    layers.Conv1D(64, 3, activation='relu', padding='same'),
    layers.MaxPooling1D(pool_size=2),
    layers.Dropout(0.3),

    layers.LSTM(128, return_sequences=True),
    layers.LSTM(64),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.4),
    layers.Dense(9, activation='softmax')  # 9개의 Attack 클래스를 위한 출력층
])

# 모델 컴파일
cnn_multi.compile(optimizer='nadam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [ ]:
# 첫 번째 모델로 테스트 데이터셋 예측
y_pred_binary = cnn_binary.predict(x_test_binary)
y_pred_binary = (y_pred_binary > 0.5).astype(int)  # Threshold 적용

# Attack으로 분류된 데이터 추출
attack_indices = np.where(y_pred_binary == 1)[0]
x_attack = x_test_binary[attack_indices]
y_attack_multi = y_multi[attack_indices]  # 다중분류 라벨


7938/7938 ━━━━━━━━━━━━━━━━━━━━ 13s 2ms/step


In [ ]:
# 다중분류 모델 학습
cnn_multi.fit(x_train_multi, y_train_multi,
              batch_size=256,
              epochs=30,
              validation_data=(x_val_multi, y_val_multi))


Epoch 1/30
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 22s 12ms/step - accuracy: 0.3535 - loss: 1.6571 - val_accuracy: 0.7615 - val_loss: 0.6913
Epoch 2/30
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 16s 12ms/step - accuracy: 0.5681 - loss: 1.0919 - val_accuracy: 0.8316 - val_loss: 0.5017
Epoch 3/30
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 15s 12ms/step - accuracy: 0.6171 - loss: 0.9536 - val_accuracy: 0.8440 - val_loss: 0.4834
Epoch 4/30
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 21s 12ms/step - accuracy: 0.6377 - loss: 0.9047 - val_accuracy: 0.8432 - val_loss: 0.4661
Epoch 5/30
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 20s 12ms/step - accuracy: 0.6560 - loss: 0.8634 - val_accuracy: 0.8452 - val_loss: 0.4646
Epoch 6/30
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 21s 12ms/step - accuracy: 0.6641 - loss: 0.8372 - val_accuracy: 0.8472 - val_loss: 0.4520
Epoch 7/30
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 20s 12ms/step - accuracy: 0.6706 - loss: 0.8190 - val_accuracy: 0.8479 - val_loss: 0.4479
Epoch 8/30
1253/1253 ━━━━━━━━━━━━━━━━━━━━ 21s 12ms/step - accuracy: 0.6765 -

In [ ]:
# attack_cat을 Label Encoding
original_label_encoder = preprocessing.LabelEncoder()
df['encoded_attack_cat'] = original_label_encoder.fit_transform(df['attack_cat'])

# y_test_multi: 원본 테스트 데이터의 10개 클래스 라벨 (0~9)
y_test_multi = df['encoded_attack_cat'].iloc[x_test_indices].values  # 테스트셋 인덱스에 맞게 선택

In [ ]:
# Multi label 매핑
original_mapping = {index: label for index, label in enumerate(original_label_encoder.classes_)}
print("Full-class Label Mapping:", original_mapping)

Full-class Label Mapping: {0: 'Analysis', 1: 'Backdoors', 2: 'DoS', 3: 'Exploits', 4: 'Fuzzers', 5: 'Generic', 6: 'Normal', 7: 'Reconnaissance', 8: 'Shellcode', 9: 'Worms'}


In [ ]:
# Multi label 매핑
multi_mapping = {index: label for index, label in enumerate(multi_label_encoder.classes_)}
print("Multi-class Label Mapping:", multi_mapping)

Multi-class Label Mapping: {0: 'Analysis', 1: 'Backdoors', 2: 'DoS', 3: 'Exploits', 4: 'Fuzzers', 5: 'Generic', 6: 'Reconnaissance', 7: 'Shellcode', 8: 'Worms'}


In [ ]:
# 이진분류 모델 예측
y_pred_binary = cnn_binary.predict(x_test_binary)  # x_test_binary: 테스트용 입력 데이터
y_pred_binary = (y_pred_binary > 0.5).astype(int)

# Attack으로 예측된 데이터 인덱스
attack_indices = np.where(y_pred_binary.flatten() == 1)[0]

# 다중분류 모델 예측
x_attack = x_test_binary[attack_indices]  # Attack으로 분류된 데이터만 추출
y_pred_multi = cnn_multi.predict(x_attack)
y_pred_multi = np.argmax(y_pred_multi, axis=1)  # 다중분류 결과 (0~8)


7938/7938 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step
994/994 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step


In [ ]:
# 이진분류 정확도 계산
binary_accuracy = accuracy_score(y_test_binary, y_pred_binary)
binary_report = classification_report(y_test_binary, y_pred_binary, target_names=['Normal', 'Attack'])
binary_cm = confusion_matrix(y_test_binary, y_pred_binary)

print(f"Binary Classification Accuracy: {binary_accuracy:}")
print("\nBinary Classification Report:\n", binary_report)
print("\nBinary Classification Confusion Matrix:\n", binary_cm)

Binary Classification Accuracy: 0.9922914903249936

Binary Classification Report:
               precision    recall  f1-score   support

      Normal       0.99      1.00      1.00    221876
      Attack       0.97      0.96      0.97     32129

    accuracy                           0.99    254005
   macro avg       0.98      0.98      0.98    254005
weighted avg       0.99      0.99      0.99    254005


Binary Classification Confusion Matrix:
 [[221059    817]
 [  1141  30988]]


In [ ]:
# 다중분류의 실제 라벨
y_actual_multi = y_test_multi[attack_indices]  # 다중분류에 해당하는 실제 라벨

# 다중분류 정확도 계산
multi_accuracy = accuracy_score(y_actual_multi, y_pred_multi)

print(f"Multi-class Classification Accuracy: {multi_accuracy:}")


Multi-class Classification Accuracy: 0.7791542210344286


In [ ]:
# 1. 최종 결과 초기화
final_predictions = np.full_like(y_test_multi, -1)  # 원본 테스트 라벨 크기에 맞게 -1로 초기화

# 2. 이진분류 결과: Normal(0)을 원본 라벨의 Normal(6)로 매핑
final_predictions[y_pred_binary.flatten() == 0] = 6  # Normal(6)

# 3. 다중분류 결과 재매핑
# attack_indices: Attack(1)으로 분류된 인덱스
for i, idx in enumerate(attack_indices):
    if y_pred_multi[i] <= 5:  # 0~5는 원본 라벨 그대로
        final_predictions[idx] = y_pred_multi[i]
    elif y_pred_multi[i] == 6:  # 다중분류의 6 → 원본 라벨의 7
        final_predictions[idx] = 7
    elif y_pred_multi[i] == 7:  # 다중분류의 7 → 원본 라벨의 8
        final_predictions[idx] = 8
    elif y_pred_multi[i] == 8:  # 다중분류의 8 → 원본 라벨의 9
        final_predictions[idx] = 9

# 4. 정확도 및 평가
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 정확도
overall_accuracy = accuracy_score(y_test_multi, final_predictions)

# 혼동 행렬
overall_cm = confusion_matrix(y_test_multi, final_predictions)

# 분류 보고서
overall_report = classification_report(y_test_multi, final_predictions)

# 결과 출력
print("Overall Accuracy:", overall_accuracy)
print("Confusion Matrix:\n", overall_cm)
print("Classification Report:\n", overall_report)


Overall Accuracy: 0.9722603885750281
Confusion Matrix:
 [[    41     73    107      1      0      0     44      0      7      0]
 [    27     91     87      1      1      1      3      2     10      0]
 [    59    407    832    163     21      2     11     24     85      4]
 [   118    484   1361   1826     39      1     93    260    171     72]
 [    64    135    149    183    867      2    918     54     50     15]
 [    12     71    186    208     31  21034      8      7     70     10]
 [     3     34     74    137    440      1 221059     56     58     14]
 [     3     53    115     10      6      0     58   1078     34      4]
 [     0      0      1      7      1      0      6      8    124      0]
 [     0      0      5      3      0      0      0      1      2      7]]
Classification Report:
               precision    recall  f1-score   support

           0       0.13      0.15      0.14       273
           1       0.07      0.41      0.12       223
           2       0.29   

In [ ]:
cnn_binary.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                      │ (None, 41, 32)              │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_1 (Conv1D)                    │ (None, 41, 32)              │           3,104 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d (MaxPooling1D)         │ (None, 20, 32)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 20, 32)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 20, 32)              │             128 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_2 (Conv1D)                    │ (None, 20, 64)              │           6,208 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_3 (Conv1D)                    │ (None, 20, 64)              │          12,352 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_1 (MaxPooling1D)       │ (None, 10, 64)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 10, 64)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 10, 64)              │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 640)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 32)                  │          20,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 127,782 (499.15 KB)

 Trainable params: 42,529 (166.13 KB)

 Non-trainable params: 192 (768.00 B)

 Optimizer params: 85,061 (332.27 KB)

In [ ]:
cnn_multi.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv1d_4 (Conv1D)                    │ (None, 41, 128)             │             512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_5 (Conv1D)                    │ (None, 41, 128)             │          49,280 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_2 (MaxPooling1D)       │ (None, 20, 128)             │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 20, 128)             │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv1d_6 (Conv1D)                    │ (None, 20, 64)              │          24,640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling1d_3 (MaxPooling1D)       │ (None, 10, 64)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 10, 64)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 10, 128)             │          98,816 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ (None, 64)                  │          49,408 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │           8,320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_4 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 9)                   │           1,161 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 696,414 (2.66 MB)

 Trainable params: 232,137 (906.79 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 464,277 (1.77 MB)